#!/bin/bash

# Check if the file /var/www/html/index.html exists
if [ -f /var/www/html/index.html ]; then
    echo "Removing existing index.html"
    rm /var/www/html/index.html
else
    echo "No index.html file to remove"
fi

# Install the httpd package
echo "Installing httpd package..."
yum install -y httpd

# Start and enable httpd service
echo "Starting and enabling httpd..."
systemctl start httpd
systemctl enable httpd
